#Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: marketpred
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
