package com.atomrockets.marketanalyzer.analyzer;

import com.atomrockets.marketanalyzer.dbManagers.GenericDBSuperclass;
import com.atomrockets.marketanalyzer.dbManagers.MarketIndexAnalysisDB;
import com.atomrockets.marketanalyzer.dbManagers.MarketIndexDB;
import com.atomrockets.marketanalyzer.dbManagers.MarketIndexParametersDB;
import com.atomrockets.marketanalyzer.analyzer.IndexAnalyzer;

import java.sql.Connection;

/**
 * This class is the highest level class that deals with all things market index.
 * Initializes and updates databases
 * Runs the model to determine buy and sell dates
 * @author Allan
 *
 */
public class MarketIndicesAnalyzer{

	//							  		  Nasdaq  S&P500
	static private String[] indexList = {"^IXIC","^GSPC","^SML","^MID"};
	static private String[] indexParametersDBNameList;

	static public void main() {

		//Get a database connection
		Connection connection = GenericDBSuperclass.getConnection();

		/*
		 * Dabase initialization Section
		 */
		//Initialize the price/volume databases for each index 
		MarketIndexDB.priceVolumeDBInitialization(connection, indexList);

		/*
		 * setting the indexParameterList to be equal to the indexList+"_var"
		 * This means adding future indices only requires adding them to one list
		 * as the indexParameterList is autogenerated from indexList
		 */
		setIndexParameterList();

		//Initialize the model variables
		MarketIndexParametersDB.indexModelParametersInitialization(connection, indexParametersDBNameList);		


		//Market Index Models
		/*
		 * Models runs are not looped because you may want to run or optimize them one at a time
		 * I'll figure out this code after I figure out the above
		 */
		
		/*
		 * Analysis data for each index is stored in a separate database. I chose this because it makes it easier
		 * to clear and repopulate when doing debugging or optimization. The analysis data table can be dropped without
		 * having to reimport all the data, which is quite time consuming.
		 * 
		 * IndexAnalysisDBInitialization checks if the table already
		 */
		MarketIndexAnalysisDB.IndexAnalysisTableInitialization(connection, indexList);
		
		IndexAnalyzer.runIndexAnalysis(connection, "^IXIC", "^IXICvars");
		//Run model for Nasdaq
		//Run model for SP500
		
		
	}

	/**
	 * This method allows for the dynamic creation of the indexParameterList
	 * The indexParameterList is simply the indexList with 'var' appended to the end
	 */
	static private void setIndexParameterList() {
		indexParametersDBNameList = new String[indexList.length];

		for(int i = 0;i<indexList.length;i++) {
			indexParametersDBNameList[i]=indexList[i] +"vars";
		}
	}
	
	static private String[] getIndexList() {
		return indexList;
	}

	static private String[] getIndexParameterList() {
		return indexParametersDBNameList;
	}
}
